/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RetrospectRouteImport } from './routes/retrospect'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MeRouteImport } from './routes/me'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedbackIdRouteImport } from './routes/feedback.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'

const RetrospectRoute = RetrospectRouteImport.update({
  id: '/retrospect',
  path: '/retrospect',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackIdRoute = FeedbackIdRouteImport.update({
  id: '/feedback/$id',
  path: '/feedback/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/recommend': typeof RecommendRoute
  '/retrospect': typeof RetrospectRoute
  '/chat/$id': typeof ChatIdRoute
  '/feedback/$id': typeof FeedbackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/recommend': typeof RecommendRoute
  '/retrospect': typeof RetrospectRoute
  '/chat/$id': typeof ChatIdRoute
  '/feedback/$id': typeof FeedbackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/recommend': typeof RecommendRoute
  '/retrospect': typeof RetrospectRoute
  '/chat/$id': typeof ChatIdRoute
  '/feedback/$id': typeof FeedbackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/me'
    | '/onboarding'
    | '/recommend'
    | '/retrospect'
    | '/chat/$id'
    | '/feedback/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/me'
    | '/onboarding'
    | '/recommend'
    | '/retrospect'
    | '/chat/$id'
    | '/feedback/$id'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/me'
    | '/onboarding'
    | '/recommend'
    | '/retrospect'
    | '/chat/$id'
    | '/feedback/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  MeRoute: typeof MeRoute
  OnboardingRoute: typeof OnboardingRoute
  RecommendRoute: typeof RecommendRoute
  RetrospectRoute: typeof RetrospectRoute
  FeedbackIdRoute: typeof FeedbackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/retrospect': {
      id: '/retrospect'
      path: '/retrospect'
      fullPath: '/retrospect'
      preLoaderRoute: typeof RetrospectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$id': {
      id: '/feedback/$id'
      path: '/feedback/$id'
      fullPath: '/feedback/$id'
      preLoaderRoute: typeof FeedbackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIdRoute: typeof ChatIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIdRoute: ChatIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  MeRoute: MeRoute,
  OnboardingRoute: OnboardingRoute,
  RecommendRoute: RecommendRoute,
  RetrospectRoute: RetrospectRoute,
  FeedbackIdRoute: FeedbackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
